modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/19Phin/Grafted-Creaking/issues"
license = "MIT"

[[mods]]
modId = "grafted_creaking_texture"
version = "${version}"
displayName = "Grafted Creaking"
authors = "DialingSpoon527"
description = '''
Adds variants to the creaking based on the wood used to spawn it.
'''
logoFile = "icon.png"

[[dependencies.grafted_creaking_texture]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.grafted_creaking_texture]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "grafted_creaking.mixins.json"
